# Generated by Django 3.2.14 on 2022-08-09 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО работника')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('employment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема на работу')),
                ('salary', models.FloatField(verbose_name='Размер зарплаты')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workers.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
