# Generated by Django 3.2.14 on 2022-08-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_set_parent_employeer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
